// packages/extension-popup/src/app/search-form/search-form.component.ts
import {
  Component,
  EventEmitter,
  Input,
  OnDestroy,
  OnInit,
  Output,
} from '@angular/core';
import {
  GoogleLanguage,
  isGoogleLanguage,
  languageList,
  LanguagePairs,
} from '@vocably/model';
import { Subject } from 'rxjs';
import { detectTargetLanguage } from '../../detectTargetLanguage';

export type SearchValues = {
  text: string;
  sourceLanguage: GoogleLanguage;
  targetLanguage: GoogleLanguage;
  isReversed: boolean;
};

const article = (phrase: string) => {
  if (
    ['a', 'e', 'i', 'o', 'y', 'u'].includes((phrase.at(0) ?? '').toLowerCase())
  ) {
    return 'an';
  } else {
    return 'a';
  }
};

@Component({
  selector: 'app-search-form',
  templateUrl: './search-form.component.html',
  styleUrls: ['./search-form.component.scss'],
})
export class SearchFormComponent implements OnInit, OnDestroy {
  @Input() isSearching = false;
  @Input() value: SearchValues | null = null;
  @Input() hideHint: boolean = false;
  @Input() languagePairs: LanguagePairs = {};
  @Output() onSubmit = new EventEmitter<SearchValues>();
  @Output() onChange = new EventEmitter<SearchValues>();

  destroy$ = new Subject<void>();

  sourceLanguage = 'en';
  targetLanguage: string = detectTargetLanguage();
  isReversed: boolean = false;
  searchText: string = '';

  preferredSourceLanguages: string[] = [];
  preferredTargetLanguages: string[] = [];

  availableSourceLanguages: string[] = [];
  availableTargetLanguages: string[] = [];

  textInputFocused = false;

  constructor() {}

  ngOnInit(): void {
    if (this.value) {
      this.sourceLanguage = this.value.sourceLanguage;
      this.targetLanguage = this.value.targetLanguage;
      this.isReversed = this.value.isReversed;
    }

    const allLanguages = Object.keys(languageList);

    this.preferredSourceLanguages = Object.keys(this.languagePairs);
    this.preferredTargetLanguages = Object.values(this.languagePairs).reduce(
      (acc, pair) => {
        return [
          ...acc,
          ...pair.possibleTargetLanguages.filter(
            (possibleLanguage) => !acc.includes(possibleLanguage)
          ),
        ];
      },
      [] as string[]
    );

    this.availableSourceLanguages = allLanguages.filter(
      (l) => !this.preferredSourceLanguages.includes(l)
    );
    this.availableTargetLanguages = allLanguages.filter(
      (l) => !this.preferredTargetLanguages.includes(l)
    );
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  submit() {
    if (this.isSearching) {
      return;
    }

    if (!isGoogleLanguage(this.sourceLanguage)) {
      return;
    }

    if (!isGoogleLanguage(this.targetLanguage)) {
      return;
    }

    this.onSubmit.emit({
      isReversed: this.isReversed,
      text: this.searchText,
      sourceLanguage: this.sourceLanguage,
      targetLanguage: this.targetLanguage,
    });
  }

  languageName(lng: string): string {
    // @ts-ignore
    return languageList[lng] ?? '';
  }

  getPlaceholderText(): string {
    if (!this.sourceLanguage || !this.targetLanguage) {
      return '';
    }

    const sourceLanguageName = this.languageName(this.sourceLanguage);
    const targetLanguageName = this.languageName(this.targetLanguage);

    if (this.isReversed) {
      return `Enter ${article(
        targetLanguageName
      )} ${targetLanguageName} word or phrase here. ${sourceLanguageName} cards will be created.`;
    }

    return `Enter any word or phrase here.`;
  }

  sourceLanguageChange() {
    // @ts-ignore
    if (this.languagePairs[this.sourceLanguage]) {
      this.targetLanguage =
        // @ts-ignore
        this.languagePairs[this.sourceLanguage].currentTargetLanguage;
    }

    this.change();
  }

  change() {
    if (this.isSearching) {
      return;
    }

    if (!isGoogleLanguage(this.sourceLanguage)) {
      return;
    }

    if (!isGoogleLanguage(this.targetLanguage)) {
      return;
    }

    this.onChange.emit({
      isReversed: this.isReversed,
      text: this.searchText,
      sourceLanguage: this.sourceLanguage,
      targetLanguage: this.targetLanguage,
    });
  }

  getSourceLanguageGroups(): any {
    const availableLanguages = [
      'Available Languages',
      this.availableSourceLanguages.map(
        (lng) => [lng, this.languageName(lng)] as const
      ),
    ] as const;

    if (this.preferredSourceLanguages.length === 0) {
      return [availableLanguages];
    }

    return [
      [
        'Preferred Langauges',
        this.preferredSourceLanguages.map(
          (lng) => [lng, this.languageName(lng)] as const
        ),
      ],
      availableLanguages,
    ];
  }

  getTargetLanguageGroups(): any {
    const availableLanguages = [
      'Available Languages',
      this.availableTargetLanguages.map(
        (lng) => [lng, this.languageName(lng)] as const
      ),
    ] as const;

    if (this.preferredTargetLanguages.length === 0) {
      return [availableLanguages];
    }

    return [
      [
        'Preferred Langauges',
        this.preferredTargetLanguages.map(
          (lng) => [lng, this.languageName(lng)] as const
        ),
      ],
      availableLanguages,
    ];
  }
}

<form
  class="search-form"
  autocomplete="off"
  (submit)="$event.preventDefault(); submit()"
>
  <div class="preset mb-0_5">
    <vocably-hint-selector
      class="language"
      hint="I study"
      [value]="sourceLanguage"
      (choose)="sourceLanguage = $event.detail; sourceLanguageChange()"
      [optionGroups]="getSourceLanguageGroups()"
    ></vocably-hint-selector>
    <div>
      <button
        type="button"
        class="direction"
        [class.reversed]="isReversed"
        (click)="isReversed = !isReversed; change()"
      >
        <mat-icon class="icon">arrow_forward</mat-icon>
      </button>
    </div>
    <vocably-hint-selector
      class="language"
      hint="I speak"
      [value]="targetLanguage"
      (choose)="targetLanguage = $event.detail; change()"
      [optionGroups]="getTargetLanguageGroups()"
    ></vocably-hint-selector>
  </div>
  <div class="search-input">
    <input
      autocomplete="off"
      aria-haspopup="false"
      autocapitalize="off"
      class="input"
      type="text"
      name="searchText"
      [placeholder]="getPlaceholderText()"
      [(ngModel)]="searchText"
      (focus)="textInputFocused = true"
      (blur)="textInputFocused = false"
    />
    <button
      class="submit"
      type="submit"
      [disabled]="isSearching || searchText.trim() === ''"
    >
      <mat-icon class="magnify" [class.animating]="isSearching"
        >search</mat-icon
      >
    </button>
  </div>
  <div *ngIf="!hideHint" style="margin-top: 1rem" class="muted">
    <style>
      .reverse-search-hint-icon {
        vertical-align: middle;
        top: -0.1rem;
        position: relative;
        cursor: pointer;
        transition: color 0.3s ease-in-out;

        &:hover {
          color: var(--emphasize-color);
        }
      }
    </style>
    <div class="hint-container">
      <ng-container *ngIf="!isReversed">
        For the improved search of {{ languageName(sourceLanguage) }} words in
        {{ languageName(targetLanguage) }} click the
        <mat-icon class="reverse-search-hint-icon" (click)="isReversed = true"
          >arrow_forward</mat-icon
        >
        button.
      </ng-container>
      <ng-container *ngIf="isReversed">
        Click
        <mat-icon class="reverse-search-hint-icon" (click)="isReversed = false"
          >arrow_back</mat-icon
        >
        button to search for cards in {{ languageName(sourceLanguage) }}.
      </ng-container>
    </div>
  </div>
</form>

// packages/extension-content-ui/src/components/search-form/search-form.tsx
import {
  Component,
  Event,
  EventEmitter,
  Fragment,
  h,
  Host,
  Prop,
  State,
} from '@stencil/core';
import {
  GoogleLanguage,
  isGoogleLanguage,
  languageList,
  LanguagePairs,
} from '@vocably/model';
import { uniq } from 'lodash-es';
import { SearchValues } from './types';

const article = (phrase: string) => {
  if (
    ['a', 'e', 'i', 'o', 'y', 'u'].includes((phrase.at(0) ?? '').toLowerCase())
  ) {
    return 'an';
  } else {
    return 'a';
  }
};

@Component({
  tag: 'vocably-search-form',
  styleUrl: 'search-form.scss',
  shadow: true,
})
export class VocablySearchForm {
  @Prop() loading: boolean = false;
  @Prop() disabled: boolean = false;
  @Prop() existingSourceLanguages: GoogleLanguage[] = [];
  @Prop() existingTargetLanguages: GoogleLanguage[] = [];
  @Prop() hideHint: boolean = false;
  @Prop() autoFocus: boolean = false;
  @Prop() languagePairs: LanguagePairs = {};

  @Prop() values: SearchValues = {
    text: '',
    sourceLanguage: 'de',
    targetLanguage: 'en',
    isReversed: false,
  };
  @Event() valuesChange: EventEmitter<SearchValues>;
  @Event() formSubmit: EventEmitter<SearchValues>;

  @State() textInputFocused: boolean = false;

  private textInput: HTMLInputElement | undefined = undefined;

  componentDidLoad() {
    if (this.autoFocus) {
      setTimeout(() => {
        this.textInput?.focus();
      }, 300);
    }
  }

  languageName(languageCode: string): string {
    // @ts-ignore
    return languageList[languageCode] ?? '';
  }

  getPlaceholderText(): string {
    if (!this.values.sourceLanguage || !this.values.targetLanguage) {
      return '';
    }

    const sourceLanguageName = this.languageName(this.values.sourceLanguage);
    const targetLanguageName = this.languageName(this.values.targetLanguage);

    if (this.values.isReversed) {
      return `Enter ${article(
        targetLanguageName
      )} ${targetLanguageName} word or phrase here. ${sourceLanguageName} cards will be created.`;
    }

    return `Enter any word or phrase here.`;
  }

  getSourceLanguageGroups(): any {
    const { preferred, available } = Object.keys(languageList).reduce<{
      preferred: string[];
      available: string[];
    }>(
      (acc, language) => {
        if (this.languagePairs.hasOwnProperty(language)) {
          return {
            ...acc,
            preferred: [...acc.preferred, language],
          };
        } else {
          return {
            ...acc,
            available: [...acc.available, language],
          };
        }
      },
      {
        preferred: [],
        available: [],
      }
    );

    const availableGroup = [
      'Available Languages',
      available.map((lng) => [lng, this.languageName(lng)] as const),
    ] as const;

    if (preferred.length === 0) {
      return [availableGroup];
    }

    return [
      [
        'Preferred Languages',
        preferred.map((lng) => [lng, this.languageName(lng)] as const),
      ],
      availableGroup,
    ];
  }

  getTargetLanguageGroups(): any {
    const allPreferredLanguages: string[] = uniq(
      Object.values(this.languagePairs).flatMap(
        (pairs) => pairs.possibleTargetLanguages
      )
    );

    const { preferred, available } = Object.keys(languageList).reduce<{
      preferred: string[];
      available: string[];
    }>(
      (acc, language) => {
        if (allPreferredLanguages.includes(language)) {
          return {
            ...acc,
            preferred: [...acc.preferred, language],
          };
        } else {
          return {
            ...acc,
            available: [...acc.available, language],
          };
        }
      },
      {
        preferred: [],
        available: [],
      }
    );

    const availableGroup = [
      'Available Languages',
      available.map((lng) => [lng, this.languageName(lng)] as const),
    ] as const;

    if (preferred.length === 0) {
      return [availableGroup];
    }

    return [
      [
        'Preferred Languages',
        preferred.map((lng) => [lng, this.languageName(lng)] as const),
      ],
      availableGroup,
    ];
  }

  getTargetLanguageCandidate(sourceLanguage: string): string {
    if (
      !isGoogleLanguage(sourceLanguage) ||
      !this.languagePairs.hasOwnProperty(sourceLanguage)
    ) {
      return this.values.targetLanguage;
    }

    return (
      this.languagePairs[sourceLanguage]?.currentTargetLanguage ??
      this.values.targetLanguage
    );
  }

  render() {
    return (
      <Host>
        <form
          class="form"
          onSubmit={(e) => {
            e.preventDefault();
            this.formSubmit.emit(this.values);
          }}
          aria-label="Search form"
        >
          <div class="preset">
            <vocably-hint-selector
              class="language"
              hint={'I study'}
              shrinkSmall={true}
              disabled={this.loading || this.disabled}
              onChoose={(event) =>
                this.valuesChange.emit({
                  ...this.values,
                  sourceLanguage: event.detail,
                  targetLanguage: this.getTargetLanguageCandidate(event.detail),
                })
              }
              value={this.values.sourceLanguage}
              optionGroups={this.getSourceLanguageGroups()}
            ></vocably-hint-selector>
            <div>
              <button
                type="button"
                class={{ direction: true, reversed: this.values.isReversed }}
                onClick={() =>
                  this.valuesChange.emit({
                    ...this.values,
                    isReversed: !this.values.isReversed,
                  })
                }
              >
                <vocably-icon-arrow-right class="icon"></vocably-icon-arrow-right>
              </button>
            </div>
            <vocably-hint-selector
              class={'language'}
              hint={'I speak'}
              shrinkSmall={true}
              disabled={this.loading || this.disabled}
              onChoose={(event) =>
                this.valuesChange.emit({
                  ...this.values,
                  targetLanguage: event.detail,
                })
              }
              value={this.values.targetLanguage}
              optionGroups={this.getTargetLanguageGroups()}
            ></vocably-hint-selector>
          </div>
          <div class="search-input">
            <input
              ref={(el) => {
                this.textInput = el;
              }}
              autocomplete="off"
              aria-haspopup="false"
              autocapitalize="off"
              class="input"
              type="text"
              name="searchText"
              placeholder={this.getPlaceholderText()}
              value={this.values.text}
              disabled={this.loading || this.disabled}
              onFocus={() => (this.textInputFocused = true)}
              onBlur={() => (this.textInputFocused = false)}
              onKeyUp={(e) => {
                this.valuesChange.emit({
                  ...this.values,
                  // @ts-ignore
                  text: e.target.value,
                });
              }}
            />
            <button
              class="submit"
              type="submit"
              disabled={this.loading || this.values.text.trim() === ''}
            >
              <vocably-icon-magnify
                class={{
                  magnify: true,
                  animating: this.loading,
                }}
              ></vocably-icon-magnify>
            </button>
          </div>
          {!this.hideHint && (
            <div class="hint">
              {!this.values.isReversed && (
                <Fragment>
                  For the improved search of{' '}
                  {this.languageName(this.values.sourceLanguage)} words in{' '}
                  {this.languageName(this.values.targetLanguage)} click the{' '}
                  <button
                    class="hint-icon-button"
                    type="button"
                    onClick={() => {
                      this.valuesChange.emit({
                        ...this.values,
                        isReversed: true,
                      });
                    }}
                  >
                    <vocably-icon-arrow-right></vocably-icon-arrow-right>
                  </button>{' '}
                  button.
                </Fragment>
              )}
              {this.values.isReversed && (
                <Fragment>
                  Click{' '}
                  <button
                    class="hint-icon-button reversed"
                    type="button"
                    onClick={() => {
                      this.valuesChange.emit({
                        ...this.values,
                        isReversed: false,
                      });
                    }}
                  >
                    <vocably-icon-arrow-right></vocably-icon-arrow-right>
                  </button>{' '}
                  button to search for cards in{' '}
                  {this.languageName(this.values.sourceLanguage)}.
                </Fragment>
              )}
            </div>
          )}
        </form>
      </Host>
    );
  }
}
